stages:
  - unit test
  - build
  - deploy
  - acceptance test

unit_test:
  stage: unit test
  script: echo "Running unit tests"

build:
  stage: build
  script: echo "Building the app"

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
    - openstack stack show $OS_STACK_NAME &>/dev/null
        && export STACK_ACTION=update || export STACK_ACTION=create
    - openstack stack $STACK_ACTION
        --parameter "project_network=$OS_PROJECT_NETWORK"
        --parameter "server_name=$OS_STACK_NAME"
        --parameter "ci_project_url=$CI_PROJECT_URL"
        --parameter "ci_build_ref=$CI_BUILD_REF"
        -t $OS_HEAT_TEMPLATE_URL -e $OS_HEAT_ENV_URL --wait $OS_STACK_NAME
    - echo "IP Address of staging server"
    - openstack stack output show $OS_STACK_NAME nginx_server_floating_ip
        -f value -c output_value
    - echo "Running acceptance tests on staging server"
  environment:
    name: staging
    url: http://training-staging.demo.opsta.io
  variables:
    OS_USERNAME: "opsta.user"
    OS_PASSWORD: "opstathailand"
    OS_PROJECT_NAME: "staging"
    OS_PROJECT_NETWORK: "staging-network"
    OS_STACK_NAME: "opsta-training-staging"
  only:
  - master

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
    - openstack stack show $OS_STACK_NAME &>/dev/null
        && export STACK_ACTION=update || export STACK_ACTION=create
    - openstack stack $STACK_ACTION
        --parameter "project_network=$OS_PROJECT_NETWORK"
        --parameter "server_name=$OS_STACK_NAME"
        --parameter "ci_project_url=$CI_PROJECT_URL"
        --parameter "ci_build_ref=$CI_BUILD_REF"
        -t $OS_HEAT_TEMPLATE_URL -e $OS_HEAT_ENV_URL --wait $OS_STACK_NAME
    - echo "IP Address of production server"
    - openstack stack output show $OS_STACK_NAME nginx_server_floating_ip
        -f value -c output_value
    - echo "Running acceptance tests on production server"
  environment:
    name: production
    url: http://training.demo.opsta.io
  variables:
    OS_USERNAME: "winggundamth"
    OS_PASSWORD: "OpstaThailand"
    OS_PROJECT_NAME: "production"
    OS_PROJECT_NETWORK: "production-network"
    OS_STACK_NAME: "opsta-training-production"
  when: manual
  only:
  - master

variables:
  OS_AUTH_URL: "https://s.opsta.io:5000/v3"
  OS_IDENTITY_API_VERSION: "3"
  OS_HEAT_TEMPLATE_URL: https://raw.githubusercontent.com/opsta/openstack-heat-workshop/master/demo/techtalkthai/stack_nginx.yml
  OS_HEAT_ENV_URL: https://raw.githubusercontent.com/opsta/openstack-heat-workshop/master/demo/techtalkthai/env_nginx_opsta_training.yml
