heat_template_version: newton

description: >
    This is HOT Templete to deploy GitLab Runner on OpenStack by HEAT orchestration


parameters:
  project_network:
    type: string
    description: Name of private network to be created
    default: project-network
  external_network:
    type: string
    description: Name of public network to allocate floating ips
    default: external-network
  image_name:
    type: string
    description: Name of image to use for instance creation
    default: ubuntu-xenial
  flavor_name:
    type: string
    description: Name of flavor to use for instance creation
    default: c1.m1
  public_key_name:
    type: string
    description: Public Key name
    default: gitlab-key
  ci_server_url:
    type: string
    description: GitLab CI Server URL
  runner_token:
    type: string
    description: GitLab CI Runner Token


resources:
  gitlab_runner_security_ping_ssh_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: ping-ssh
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp

  gitlab_runner_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: external_network }

  gitlab_runner_floating_ip_association:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: gitlab_runner_floating_ip }
      port_id: { get_attr: [gitlab_runner_server, addresses, operation-network, 0, port] }

  gitlab_runner_server:
    type: OS::Nova::Server
    properties:
      name: gitlab-runner
      block_device_mapping_v2:
        - device_name: vda
          volume_size: 16
          image: { get_param: image_name }
      flavor: { get_param: flavor_name }
      key_name: { get_param: public_key_name }
      networks:
        - network: { get_param: project_network }
      security_groups:
        - { get_resource: gitlab_runner_security_ping_ssh_group }
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-ci-multi-runner/script.deb.sh | bash
            apt-get install -y gitlab-ci-multi-runner
            gitlab-ci-multi-runner register -n -u $CI_SERVER_URL -r $RUNNER_TOKEN --executor shell --name gitlab-runner
          params:
            $CI_SERVER_URL: { get_param: ci_server_url }
            $RUNNER_TOKEN: { get_param: runner_token }


outputs:
    gitlab_runner_server_floating_ip:
        description: GitLab Runner Server Floating IP
        value: { get_attr: [gitlab_runner_server, networks, operation-network, 1] }
