heat_template_version: newton

description: Create Cirros instance with parameters

parameters:
    instance_name:
        type: string
        description: Instance Name
        default: cirros-heat
    image_name:
        type: string
        description: Image Name
        default: cirros-0.3.4-x86_64
    flavor_name:
        type: string
        description: Flavor name
        default: c1.m1
    private_network_name:
        type: string
        description: Project Network Name
        default: opsta-network
    external_network_name:
        type: string
        description: External Network Name
        default: external-network
    security_group_ping_ssh_name:
        type: string
        description: Name of ping and ssh security group
        default: opsta-ping-ssh
    public_key:
        type: string
        description: Public key to assign to instance
        default: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCuCi8o29fDdmo3b0LcWZmAHn83Anv5wrYpJSiv7QGlog567nFMhfTKpv3f1OBHHYhIHCNwasciw8JUu9tR270idhAXjtSyFW2d59YGKO+PLVGBOWpjRGbTQMrrGeOZ8PT/tRKZzYYJOvNQoDn+smjPZsHNB929LFdIlfyu1iUPd7DR4KLONIwB2glLtKpesQm01fqSo1clRK5NFKu6UH8iIowTTLorSDkVSSg2rxIj+7z5zvDuGaTyxRmfH36Z7YftSBDloG9aY73MWq5dQPOAWD2OIggP2CmypTuPwZ/a+nHgiJNKCblDygm4b0DaTFts3LJUYCpP6pW7+p8qq69D training@opsta
    public_key_name:
        type: string
        description: Public Key Name
        default: my_key

resources:
  instance:
    type: OS::Nova::Server
    properties:
      name: { get_param: instance_name }
      image: { get_param: image_name }
      flavor: { get_param: flavor_name }
      key_name: { get_resource: key_pair }
      security_groups:
        - { get_resource: security_group_ping_ssh }
      networks:
        - network: { get_param: private_network_name }

  security_group_ping_ssh:
    type: OS::Neutron::SecurityGroup
    properties:
      name: { get_param: security_group_ping_ssh_name }
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp

  key_pair:
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: public_key_name }
      public_key: { get_param: public_key }

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: external_network_name }

  associate_floating_ip:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: floating_ip }
      port_id: { get_attr: [instance, addresses, { get_param: private_network_name }, 0, port] }
